### ISSUE TITLE
Create a hello world database through ACK RDS controller

### ISSUE THREAD

**Issue by ali-tm-amin** [elifesciences/elife-flux-cluster#2788]

**Comment by giorgiosironi** [comment]
To test connecting:
```
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: journal
spec:
  containers:
   - image: postgres:14
     name: myapp
     command:
        - psql
     imagePullPolicy: IfNotPresent
     env:
      - name: PGHOST
        valueFrom:
         configMapKeyRef:
          name: helloworld-connection
          key: "journal.helloworld-host"
      - name: PGPORT
        valueFrom:
         configMapKeyRef:
          name: helloworld-connection
          key: "journal.helloworld-port"
      - name: PGUSER
        valueFrom:
         configMapKeyRef:
          name: helloworld-connection
          key: "journal.helloworld-user"
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
           name: "helloworld-password"
           key: password
```
